'''
This module will run different prediction models on different set
of features (aka `feature candidates` such as Sbert, Holbert, ABSAPP etc),
aiming to target different `problems` (csv data generated by create_dataset module, 
refer to create_dataset module for data format).

This means that for M models, P problems, F features, there is
M * P * F number of experienments

## Model
Each model will be specified with a unique name, so that the same model
can be instantiated with variety of configurations to look at different possibilities
Configuration:
    {
    name : exampleModel, # unique name given to each model
    participating:    : true, # to include in analysis or not
    subModule : 'KNN', # will look for `Model` modules/feature_competition/models/KNN.py
    subModuleConfig: {k = 3} # configuration given to the model
    }
Each submodel/main.py should have a wrapper class `ModelInterface()` that upon
calling will return a object implementing `Model` interface in 
feature_competition/models/Interface.py

## problems

problem configuration accepts two format:

specify the file path and control the participation of each file 
problems      : [
                  {
                    directory         : ../data/intermediate/create_dataset/2022-01-21_15-02-38/anhedoniaPresent.csv,
                    participating     : true,
                  },{
                    directory         : ../data/intermediate/create_dataset/2022-01-21_15-02-38/cognitionIssue.csv,
                    participating     : true,
                  }
]

The following format takes in a directory and include all files in the directory 
to the problem:
problems      : ../data/intermediate/create_dataset/2022-01-21_18-15-12_5initialLabels

Only the one specified behind in sequential order will be accepted if both are written


## Features


    {
        name              : vanillaHolbert,
        participating     : true,
        subModule         : holbert,
        subModuleConfig   : {}
    }
Will be looking for `Feature` in feature_competition/features/holbert.py
`Feature` should implement `FeatureInterface` found in feature_competition/features/Interface.py


'''